name: 🚀 Build WebView Android APK (Saad)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🤖 Setup Android SDK (Fixed)
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          accept-android-sdk-licenses: true

      - name: 🧱 Create Android WebView Project
        run: |
          mkdir -p android/app/src/main/java/com/saad/webview
          mkdir -p android/app/src/main/res/values

          # MainActivity.java
          cat <<'EOF' > android/app/src/main/java/com/saad/webview/MainActivity.java
          package com.saad.webview;
          import android.os.Bundle;
          import android.webkit.WebView;
          import android.webkit.WebSettings;
          import androidx.appcompat.app.AppCompatActivity;

          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  WebView webView = new WebView(this);
                  setContentView(webView);
                  WebSettings settings = webView.getSettings();
                  settings.setJavaScriptEnabled(true);
                  settings.setDomStorageEnabled(true);
                  settings.setLoadWithOverviewMode(true);
                  settings.setUseWideViewPort(true);
                  webView.loadUrl("https://saadiraq2025-cyber.github.io/saad/");
              }
          }
          EOF

          # AndroidManifest.xml
          cat <<'EOF' > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.saad.webview">
              <uses-permission android:name="android.permission.INTERNET" />
              <application
                  android:label="Saad WebView"
                  android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

          # build.gradle files
          cat <<'EOF' > android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath 'com.android.tools.build:gradle:8.0.2' }
          }
          allprojects { repositories { google(); mavenCentral() } }
          EOF

          cat <<'EOF' > android/app/build.gradle
          apply plugin: 'com.android.application'

          android {
              compileSdkVersion 34
              defaultConfig {
                  applicationId "com.saad.webview"
                  minSdkVersion 24
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
          }

          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
          }
          EOF

          echo "✅ Android WebView project structure ready"

      - name: 🔨 Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease
          mkdir -p ../my-apks
          cp app/build/outputs/apk/release/app-release.apk ../my-apks/
          echo "✅ APK built successfully!"

      - name: 📤 Upload WebView APK
        uses: actions/upload-artifact@v4
        with:
          name: Saad-WebView
          path: my-apks/
