name: Build Android APK/AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Cordova
      run: npm install -g cordova
    
    - name: Install dependencies
      run: npm install || true
    
    - name: Add Android platform
      run: cordova platform add android
    
    - name: Build Debug APK
      run: cordova build android --debug
    
    - name: Build Release APK
      run: cordova build android --release
    
    - name: Build AAB
      run: cordova build android --release -- --packageType=bundle
    
    - name: Upload APK Debug
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
    
    - name: Upload APK Release
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
    
    - name: Upload AAB Release
      uses: actions/upload-artifact@v3
      with:
        name: app-bundle
        path: platforms/android/app/build/outputs/bundle/release/app-release.aab
