name: 🔐 Build Signed WebView APK & AAB (Saad)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🤖 Setup Android SDK (Fixed Compatibility)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools
          sudo unzip -q cmdtools.zip -d /usr/local/lib/android/sdk/cmdline-tools
          sudo mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: 🔑 Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore saad-key.keystore \
            -alias saadkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass saad2025 \
            -keypass saad2025 \
            -dname "CN=Saad, OU=AI, O=Saad, L=Baghdad, S=IQ, C=IQ"

      - name: 🧱 Create Android WebView Project
        run: |
          mkdir -p android/app/src/main/java/com/saad/webview
          mkdir -p android/app/src/main/res/values

          # MainActivity.java
          cat <<'EOF' > android/app/src/main/java/com/saad/webview/MainActivity.java
          package com.saad.webview;
          import android.os.Bundle;
          import android.webkit.WebView;
          import android.webkit.WebSettings;
          import androidx.appcompat.app.AppCompatActivity;

          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  WebView webView = new WebView(this);
                  setContentView(webView);
                  WebSettings settings = webView.getSettings();
                  settings.setJavaScriptEnabled(true);
                  settings.setDomStorageEnabled(true);
                  settings.setLoadWithOverviewMode(true);
                  settings.setUseWideViewPort(true);
                  webView.loadUrl("https://saadiraq2025-cyber.github.io/saad/");
              }
          }
          EOF

          # AndroidManifest.xml
          cat <<'EOF' > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.saad.webview">
              <uses-permission android:name="android.permission.INTERNET" />
              <application
                  android:label="Saad WebView"
                  android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

          # build.gradle files
          cat <<'EOF' > android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath 'com.android.tools.build:gradle:8.0.2' }
          }
          allprojects { repositories { google(); mavenCentral() } }
          EOF

          cat <<'EOF' > android/app/build.gradle
          apply plugin: 'com.android.application'

          android {
              compileSdkVersion 34
              defaultConfig {
                  applicationId "com.saad.webview"
                  minSdkVersion 24
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0"
              }
              signingConfigs {
                  release {
                      storeFile file('../../saad-key.keystore')
                      storePassword 'saad2025'
                      keyAlias 'saadkey'
                      keyPassword 'saad2025'
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                      minifyEnabled false
                  }
              }
          }

          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
          }
          EOF

          echo "✅ Android WebView project created"

      - name: 🔨 Build Signed APK & AAB
        run: |
          cd android
          ./gradlew assembleRelease bundleRelease
          mkdir -p ../signed-builds
          cp app/build/outputs/apk/release/app-release.apk ../signed-builds/Saad-WebView-Signed.apk
          cp app/build/outputs/bundle/release/app-release.aab ../signed-builds/Saad-WebView-Signed.aab
          echo "✅ APK & AAB built successfully!"

      - name: 📤 Upload Signed Files
        uses: actions/upload-artifact@v4
        with:
          name: Saad-WebView-Signed
          path: signed-builds/
